"""
cppyy_kit.stubgen -- generate a ``.pyi`` stub for a kit's public Python surface.

A kit *mirrors* a C++ API, but the mirror is assembled at runtime (functions,
constants, patched classes), so an IDE / mypy sees nothing useful. This emits a
static ``.pyi`` for the kit **module's public surface** -- its functions, classes
(with methods) and constants -- so editors get name + arity completion and mypy a
corridor.

    python -m cppyy_kit stubgen bt_kit -o bt_kit/__init__.pyi

Honest scope (documented in the generated header): this stubs the *kit's Python
API*, the part that is statically knowable. It does NOT stub the C++ namespace a
bringup returns (``cppyy.gbl.BT.*`` etc.) -- those are dynamic cppyy proxies with no
static signatures, so a bringup's return type is ``Any``. Signatures are emitted as
names + arity with ``Any`` types (always-valid, loose) rather than guessed C++
types, which is the reliable corridor; tighten by hand where a kit wants richer
hints. Regenerate when the kit's surface changes (a test can diff it)."""
import inspect
import sys

_CONST_TYPES = {int: "int", float: "float", bool: "bool", str: "str", bytes: "bytes"}


def _sig_params(fn):
    try:
        sig = inspect.signature(fn)
    except (ValueError, TypeError):
        return None
    parts = []
    for p in sig.parameters.values():
        s = p.name
        if p.kind is p.VAR_POSITIONAL:
            s = "*" + s
        elif p.kind is p.VAR_KEYWORD:
            s = "**" + s
        if p.default is not inspect.Parameter.empty:
            s += " = ..."
        parts.append(s)
    return parts


def _fn_stub(name, fn, indent=""):
    params = _sig_params(fn)
    if params is None:
        return "%sdef %s(*args, **kwargs) -> Any: ..." % (indent, name)
    return "%sdef %s(%s) -> Any: ..." % (indent, name, ", ".join(params))


def _class_stub(name, cls):
    bases = [b.__name__ for b in cls.__bases__ if b is not object]
    header = "class %s%s:" % (name, ("(%s)" % ", ".join(bases)) if bases else "")
    lines = []
    for mname, member in sorted(vars(cls).items()):
        if mname != "__init__" and mname.startswith("_"):
            continue
        if inspect.isfunction(member):
            lines.append(_fn_stub(mname, member, "    "))
    if not lines:
        lines.append("    ...")
    return header + "\n" + "\n".join(lines)


def stub_module(module):
    """Return ``.pyi`` text for ``module``'s public surface (names not starting with
    ``_``, defined in the module -- functions, classes, and scalar constants)."""
    name = module.__name__

    def _ours(obj):
        # defined in the module or re-exported from one of its submodules (so a
        # package __init__ that re-exports from .cache/.require/... is covered)
        mod = getattr(obj, "__module__", None)
        return mod is not None and (mod == name or mod.startswith(name + "."))

    funcs, classes, consts = [], [], []
    for attr in sorted(dir(module)):
        if attr.startswith("_"):
            continue
        obj = getattr(module, attr)
        if inspect.isfunction(obj):
            if _ours(obj):
                funcs.append((attr, obj))
        elif inspect.isclass(obj):
            if _ours(obj):
                classes.append((attr, obj))
        elif type(obj) in _CONST_TYPES:
            consts.append((attr, _CONST_TYPES[type(obj)]))

    out = [
        "# Auto-generated by `python -m cppyy_kit stubgen %s` -- do not edit by hand." % name,
        "# Stubs the kit's public Python surface (names + arity, Any-typed). The C++",
        "# namespace a bringup returns is dynamic (cppyy proxies) and is not stubbed.",
        "from typing import Any",
        "",
    ]
    for cname, cval in consts:
        out.append("%s: %s" % (cname, cval))
    if consts:
        out.append("")
    for fname, fobj in funcs:
        out.append(_fn_stub(fname, fobj))
    if funcs:
        out.append("")
    for cname, cobj in classes:
        out.append(_class_stub(cname, cobj))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _main(argv):
    import argparse
    ap = argparse.ArgumentParser(prog="python -m cppyy_kit stubgen",
                                 description="Generate a .pyi for a kit's public surface.")
    ap.add_argument("module", help="importable module name, e.g. bt_kit")
    ap.add_argument("-o", "--output", help="write here (default: stdout)")
    args = ap.parse_args(argv)
    import importlib
    text = stub_module(importlib.import_module(args.module))
    if args.output:
        with open(args.output, "w") as fh:
            fh.write(text)
        sys.stderr.write("wrote %s (%d bytes)\n" % (args.output, len(text)))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
