"""
``cppyy_kit.stubgen`` generates a ``.pyi`` stub for a kit's public Python API.

A kit builds its Python API at runtime from functions, constants, and patched
classes. This makes the API hard for IDEs and mypy to inspect. This module emits a
static ``.pyi`` for the kit's public functions, classes, methods, and constants.
Editors can then complete names and arguments, and mypy can check calls.

    python -m cppyy_kit stubgen bt_kit -o bt_kit/__init__.pyi

The generated stub covers the kit's Python API. It does not cover the C++
namespace returned by bringup (such as ``cppyy.gbl.BT.*``). Those are dynamic
cppyy proxies without static signatures, so the bringup return type is ``Any``.
The stub includes parameter names and argument counts, with ``Any`` types. This
avoids guessing C++ types. Add more specific types by hand when needed. Regenerate
the stub when the kit API changes; tests can compare it with the checked-in file."""
import inspect
import sys
import typing

_CONST_TYPES = {int: "int", float: "float", bool: "bool", str: "str", bytes: "bytes"}


def _sig_params(fn):
    try:
        sig = inspect.signature(fn)
    except (ValueError, TypeError):
        return None
    parts = []
    for p in sig.parameters.values():
        s = p.name
        if p.kind is p.VAR_POSITIONAL:
            s = "*" + s
        elif p.kind is p.VAR_KEYWORD:
            s = "**" + s
        if p.default is not inspect.Parameter.empty:
            s += " = ..."
        parts.append(s)
    return parts


def _fn_stub(name, fn, indent=""):
    params = _sig_params(fn)
    if params is None:
        return "%sdef %s(*args, **kwargs) -> Any: ..." % (indent, name)
    return "%sdef %s(%s) -> Any: ..." % (indent, name, ", ".join(params))


def _class_stub(name, cls):
    bases = [b.__name__ for b in cls.__bases__ if b is not object]
    header = "class %s%s:" % (name, ("(%s)" % ", ".join(bases)) if bases else "")
    lines = []
    for mname, member in sorted(vars(cls).items()):
        if mname != "__init__" and mname.startswith("_"):
            continue
        if inspect.isfunction(member):
            lines.append(_fn_stub(mname, member, "    "))
    if not lines:
        lines.append("    ...")
    return header + "\n" + "\n".join(lines)


def stub_module(module):
    """Return ``.pyi`` text for public functions, classes, and scalar constants
    defined in ``module``. Names starting with ``_`` are excluded."""
    name = module.__name__

    def _ours(obj):
        # defined in the module or re-exported from one of its submodules (so a
        # package __init__ that re-exports from .cache/.require/... is covered)
        mod = getattr(obj, "__module__", None)
        return mod is not None and (mod == name or mod.startswith(name + "."))

    funcs, classes, consts, aliases = [], [], [], []
    for attr in sorted(dir(module)):
        if attr.startswith("_"):
            continue
        obj = getattr(module, attr)
        if (name == "cppyy_kit" and attr == "ConstNDArray" and
                typing.get_origin(obj) is typing.Annotated):
            aliases.append("from ._array_annotations import ConstNDArray as ConstNDArray")
        elif inspect.isfunction(obj):
            if _ours(obj):
                funcs.append((attr, obj))
        elif inspect.isclass(obj):
            if _ours(obj):
                classes.append((attr, obj))
        elif type(obj) in _CONST_TYPES:
            consts.append((attr, _CONST_TYPES[type(obj)]))

    out = [
        "# Auto-generated by `python -m cppyy_kit stubgen %s` -- do not edit by hand." % name,
        "# Stubs the kit's public Python surface (names + arity, Any-typed). The C++",
        "# namespace a bringup returns is dynamic (cppyy proxies) and is not stubbed.",
        "from typing import Any",
    ]
    out.extend(aliases)
    out.append("")
    for cname, cval in consts:
        out.append("%s: %s" % (cname, cval))
    if consts:
        out.append("")
    for fname, fobj in funcs:
        out.append(_fn_stub(fname, fobj))
    if funcs:
        out.append("")
    for cname, cobj in classes:
        out.append(_class_stub(cname, cobj))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _main(argv):
    import argparse
    ap = argparse.ArgumentParser(prog="python -m cppyy_kit stubgen",
                                 description="Generate a .pyi for a kit's public surface.")
    ap.add_argument("module", help="importable module name, e.g. bt_kit")
    ap.add_argument("-o", "--output", help="write here (default: stdout)")
    args = ap.parse_args(argv)
    import importlib
    text = stub_module(importlib.import_module(args.module))
    if args.output:
        with open(args.output, "w") as fh:
            fh.write(text)
        sys.stderr.write("wrote %s (%d bytes)\n" % (args.output, len(text)))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
